### ISSUE TITLE
有个疑问，微信JS-SDK-分享接口不是要认证过的公众号才能使用吗

### ISSUE THREAD

**Issue by johanazhu** [wforguo/wechat#1]
如题，我看你的 demo：https://forguo.cn/app  在微信中能直接分享（能看到缩略图和自定义文字描述），但据我所知，微信JS-SDK-分享接口是要认证过的公众号才有的使用，所以你是交了300块钱的认证费吗

**Comment by wforguo** [comment]
因为我的公众号属于个人，所以不需要交钱，【貌似现在个人不能认证，我是2016年注册的】，
只有企业认证才需要去交钱

**Comment by johanazhu** [comment]
感谢回复，应该不是个人的原因。微信文档上写了。https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Explanation_of_interface_privileges.html
只有认证过的账号才能调用微信的 js-sdk 的分享接口，就很奇怪为什么能分享

**Comment by johanazhu** [comment]
社区里有人问过：https://developers.weixin.qq.com/community/develop/doc/000e60dc0c8e888d5f3bd442856000?_at=1641978387175 
所以很奇怪你的能调通

**Comment by wforguo** [comment]
![image](https://user-images.githubusercontent.com/23009078/149097897-6cd3c403-7b65-4103-962b-bf2f38def78f.png)

![image](https://user-images.githubusercontent.com/23009078/149098214-b59226b0-489f-417c-8569-2c5f8cb9a80d.png)

是的，现在是企业账号需要交钱认证，个人账号现在不让认证，
应该是早期不需要认证就可以使用，后期补上了这个漏洞，
我的是2016年注册的公众号

**Comment by johanazhu** [comment]
我的情况和你一样，我是15年8月份申请的个人订阅号。之前做微信分享时拿自己的订阅号做过微信分享，但是分享功能不能接通 Orz

**Comment by johanazhu** [comment]
应该是早期不需要认证就可以使用，后期补上了这个漏洞
----------------------------------------------------------------
晚点跑下代码试试（或许是早期代码写的差点意思）

**Comment by johanazhu** [comment]
今天尝试了下，在本地跑的通，但是线上不行，jssdk权限和你一样，都是空白，但是你的js config end 能接受到，我的收不到

算了，还以为有这个漏洞可以钻呢 Orz
